spring:
  application:
    name: Test Automation API Case Solution

webclient:
  connect-timeout: 5000  # milliseconds
  read-timeout: 10000    # milliseconds
  max-memory-size: 512  # megabyte

client:
  pet:
    findByStatus: /v2/pet/findByStatus
    addNewPet: /v2/pet
    findPetById: /v2/pet/%s
    updateExistingPet: /v2/pet
    uploadAnImage: /v2/pet/%s/uploadImage
    updatePetInStoreWithFormData: /v2/pet/%s
    deleteAPet: /v2/pet/%s

test-resilience:
  rest:
    pet:
      find-by-status:
        delay: 500 # milliseconds
        attempt: 10
      update-with-form:
        delay: 500
        attempt: 20


logging:
  file:
    name: .logs/test-logs.log
  level:
    com.insider.testcase.test_automation_api.pet.client.logging.PetClientLoggingAspect: DEBUG
