name: Api Tests

on:
  push:
    branches: [ master ]
    paths:
      - 'test-automation-api/**'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-and-report:
    runs-on: ubuntu-latest
    env:
      PET_STORE_API_KEY: ${{ secrets.PET_STORE_API_KEY }}
    defaults:
      run:
        working-directory: test-automation-api

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Temurin JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '24'
          cache: maven

      - name: Set Spring profile
        run: echo "SPRING_PROFILES_ACTIVE=pipeline" >> $GITHUB_ENV

      - name: Build & test (creates Allure report during verify)
        run: |
          mvn -U -B -ntp clean verify -Dmaven.test.failure.ignore=true

      - name: Upload allure-results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: test-automation-api/target/allure-results/**
          if-no-files-found: warn
          retention-days: 3

      - name: Upload allure-report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: test-automation-api/target/allure-report/**
          if-no-files-found: warn
          retention-days: 3

      - name: Upload surefire-reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: test-automation-api/target/surefire-reports/**
          if-no-files-found: ignore

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: app-logs
          path: test-automation-api/.logs
          if-no-files-found: warn
          retention-days: 3

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: test-automation-api/target/allure-report

  deploy-pages:
    needs: test-and-report
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Add link to job summary
        run: |
          echo "### ✅ Allure report" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.deployment.outputs.page_url }}" >> $GITHUB_STEP_SUMMARY