name: UI Tests

on:
  push:
    branches: [ master ]
    paths:
      - 'test-automation/**'
      - '.github/workflows/ui-test.yml'
  pull_request:
  workflow_dispatch:

defaults:
  run:
    working-directory: test-automation

concurrency:
  group: ui-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ui-e2e:
    name: UI on ${{ matrix.browser }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [ chrome, firefox ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Temurin JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '24'
          cache: maven

      - name: Setup Chrome
        if: matrix.browser == 'chrome'
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Setup Firefox
        if: matrix.browser == 'firefox'
        uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: latest

      - name: Show browser versions
        run: |
          google-chrome --version || true
          firefox --version || true

      - name: Run tests
        run: mvn clean verify -Dmaven.test.failure.ignore=true

      - name: Upload JUnit reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports-${{ matrix.browser }}
          path: test-automation/target/surefire-reports/**
          if-no-files-found: warn
          retention-days: 3

      - name: Upload failure screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots-${{ matrix.browser }}
          path: test-automation/target/screenshots/**
          if-no-files-found: warn
          retention-days: 3

      - name: Upload allure-results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: test-automation/target/allure-results/**
          if-no-files-found: warn
          retention-days: 3

      - name: Upload allure-report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: test-automation/target/allure-report/**
          if-no-files-found: warn
          retention-days: 3

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: test-automation/target/allure-report

  deploy-pages:
    needs: ui-e2e
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Add link to job summary
        run: |
          echo "### ✅ Allure report" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.deployment.outputs.page_url }}" >> $GITHUB_STEP_SUMMARY